In [23]:
# Imports
import csv
import pandas as pd
import requests
import bs4
from bs4 import BeautifulSoup
import json
import numpy as np 
from pandas.io.json import json_normalize

In [24]:
# %% Setup version

print('pandas version: {}'.format(pd.__version__))
print('bs4 version: {}'.format(bs4.__version__))
print('requests version: {}'.format(requests.__version__))
print('csv version: {}'.format(csv.__version__))
print('json version: {}'.format(json.__version__))
print('numpy version: {}'.format(np.__version__))

pandas version: 1.4.2
bs4 version: 4.11.1
requests version: 2.27.1
csv version: 1.0
json version: 2.0.9
numpy version: 1.21.5

In [2]:
base_url = 'https://understat.com/player/'
# Position or roles of football players
Roles = ['AMC','DR','DMR','MR','AMR','FWR','FWL','Sub','AML','FW','FWL','DML','DC','DL','DR','ML']

def playerShots(id):
    
    url = base_url + str(id)
    result = requests.get(url)
    soup = BeautifulSoup(result.content, 'lxml')
    scripts = soup.find_all('script')
    shots = scripts[3].string
    index_start = shots.index("('")+2
    index_end = shots.index("')")
    json_data = shots[index_start:index_end]
    json_data = json_data.encode('utf8').decode('unicode_escape') 
    data = json.loads(json_data)
    df = pd.DataFrame.from_dict(data)
    
    for r in range(len(df.index)):
        df.X[r]=pd.to_numeric(df.X[r])*100.0
        df.Y[r]=pd.to_numeric(df.Y[r])*100.0
        
    return df

In [4]:
kb10_shots= playerShots(2370)
kb10_shots

,id,minute,result,X,Y,xG,player,h_a,player_id,situation,season,shotType,match_id,h_team,a_team,h_goals,a_goals,date,player_assisted,lastAction
0,32539,29,Goal,92.199997,48.5,0.05488787591457367,Karim Benzema,h,2370,FromCorner,2014,Head,5834,Real Madrid,Cordoba,2,0,2014-08-25 19:00:00,Toni Kroos,Aerial
1,32695,68,BlockedShot,82.900002,31.799999,0.050836652517318726,Karim Benzema,a,2370,OpenPlay,2014,RightFoot,5844,Real Sociedad,Real Madrid,4,2,2014-08-31 20:00:00,Isco,Pass
2,32703,90,ShotOnPost,91.5,54.0,0.3774489462375641,Karim Benzema,a,2370,OpenPlay,2014,LeftFoot,5844,Real Sociedad,Real Madrid,4,2,2014-08-31 20:00:00,James Rodríguez,Rebound
3,32914,18,MissedShots,80.300003,69.900002,0.025250796228647232,Karim Benzema,h,2370,OpenPlay,2014,RightFoot,5789,Real Madrid,Atletico Madrid,1,2,2014-09-13 19:00:00,James Rodríguez,Pass
4,32920,37,MissedShots,79.0,65.300003,0.03066813200712204,Karim Benzema,h,2370,OpenPlay,2014,RightFoot,5789,Real Madrid,Atletico Madrid,1,2,2014-09-13 19:00:00,Gareth Bale,TakeOn
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
807,493764,68,MissedShots,78.199997,45.200001,0.04331313073635101,Karim Benzema,h,2370,OpenPlay,2022,LeftFoot,19046,Real Madrid,Barcelona,3,1,2022-10-16 14:15:00,Federico Valverde,Pass
808,494478,10,BlockedShot,91.900002,55.799999,0.4669930934906006,Karim Benzema,a,2370,OpenPlay,2022,LeftFoot,19054,Elche,Real Madrid,0,3,2022-10-19 19:00:00,Vinícius Júnior,Pass
809,494488,49,SavedShot,67.800003,67.099998,0.014357560314238071,Karim Benzema,a,2370,OpenPlay,2022,RightFoot,19054,Elche,Real Madrid,0,3,2022-10-19 19:00:00,Vinícius Júnior,Pass
810,494489,59,BlockedShot,80.599998,51.5,0.06716801226139069,Karim Benzema,a,2370,OpenPlay,2022,RightFoot,19054,Elche,Real Madrid,0,3,2022-10-19 19:00:00,Vinícius Júnior,Pass
811,494492,74,Goal,84.400002,48.700001,0.09749694168567657,Karim Benzema,a,2370,OpenPlay,2022,RightFoot,19054,Elche,Real Madrid,0,3,2022-10-19 19:00:00,Rodrygo,Pass

In [5]:
def matchesData(id):
    
    url = base_url + str(id)
    result = requests.get(url)
    soup = BeautifulSoup(result.content)
    scripts = soup.find_all('script')
    matches_data = scripts[4].string
    index_start = matches_data.index("('")+2
    index_end = matches_data.index("')")
    json_data = matches_data[index_start:index_end]
    json_data = json_data.encode('utf8').decode('unicode_escape')
    data = eval(json_data)
    df = pd.DataFrame.from_dict(data)
    
    return df

In [6]:
kb10_matches= matchesData(2370)
kb10_matches

,goals,shots,xG,time,position,h_team,a_team,h_goals,a_goals,date,id,season,roster_id,xA,assists,key_passes,npg,npxG,xGChain,xGBuildup
0,1,4,0.6460156440734863,90,FW,Elche,Real Madrid,0,3,2022-10-19,19054,2022,557633,0.11982376873493195,0,1,1,0.6460156440734863,1.372884750366211,1.2753877639770508
1,1,2,0.13236631453037262,89,FW,Real Madrid,Barcelona,3,1,2022-10-16,19046,2022,556796,0.06342621892690659,0,1,1,0.13236631453037262,0.2708408236503601,0.0750482976436615
2,0,4,1.4183217287063599,90,FW,Real Madrid,Osasuna,1,1,2022-10-02,19030,2022,553514,0.17267689108848572,0,3,0,0.6750441193580627,0.8217079639434814,0
3,0,4,0.9390552043914795,90,FW,Real Madrid,Real Betis,2,1,2022-09-03,18996,2022,547313,0.15193842351436615,0,4,0,0.9390552043914795,1.5936683416366577,0.6327095031738281
4,2,8,1.0893410444259644,90,FW,Espanyol,Real Madrid,1,3,2022-08-28,18989,2022,545722,0.04379674047231674,0,1,2,1.0893410444259644,1.421626329421997,0.6161652207374573
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
258,0,1,0.1468411237001419,84,FW,Villarreal,Real Madrid,0,2,2014-09-27,5817,2014,37171,0.527085542678833,1,1,0,0.1468411237001419,0.7495651245117188,0.07563851028680801
259,0,2,0.1097874864935875,59,FW,Deportivo La Coruna,Real Madrid,2,8,2014-09-20,5797,2014,37226,0.9087657928466797,2,3,0,0.1097874864935875,1.0433579683303833,0.07410747557878494
260,0,3,0.14278748631477356,63,FW,Real Madrid,Atletico Madrid,1,2,2014-09-13,5789,2014,36605,0,0,0,0,0.14278748631477356,0.14278748631477356,0
261,0,2,0.4282855987548828,90,FW,Real Sociedad,Real Madrid,4,2,2014-08-31,5844,2014,36340,0.12400013953447342,0,1,0,0.4282855987548828,0.5900992751121521,0.037813540548086166
262,1,1,0.05488787591457367,76,FW,Real Madrid,Cordoba,2,0,2014-08-25,5834,2014,36158,0.07663362473249435,0,1,1,0.05488787591457367,0.07663362473249435,0

In [8]:
def allPlayerData(id):
    
    url = base_url + str(id)
    result = requests.get(url)
    soup = BeautifulSoup(result.content)
    scripts = soup.find_all('script')
    g_data = scripts[1].string
    index_start = g_data.index("('")+2
    index_end = g_data.index("')")
    json_data = g_data[index_start:index_end]
    json_data = json_data.encode('utf8').decode('unicode_escape')
    data = eval(json_data)
    df = json_normalize(data)
    position_data = json_normalize(df['season'][0])
    
    return  position_data

In [9]:
kb10_total= allPlayerData(2370)
kb10_total

C:\Users\pc\AppData\Local\Temp\ipykernel_13708\1351148052.py:13: FutureWarning: pandas.io.json.json_normalize is deprecated, use pandas.json_normalize instead.
  df = json_normalize(data)
C:\Users\pc\AppData\Local\Temp\ipykernel_13708\1351148052.py:14: FutureWarning: pandas.io.json.json_normalize is deprecated, use pandas.json_normalize instead.
  position_data = json_normalize(df['season'][0])

,position,games,goals,shots,time,xG,assists,xA,key_passes,season,team,yellow,red,npg,npxG,xGChain,xGBuildup
0,FW,7,5,34,629,7.828226819634438,1,1.0508344769477844,15,2022,Real Madrid,0,0,4,6.3416715413331985,8.153824746608734,2.8006817623972893
1,FW,32,27,128,2614,24.671552054584026,12,8.996260192245245,62,2021,Real Madrid,0,0,20,16.495626024901867,28.83271423354745,9.545944466721267
2,FW,34,23,123,2914,19.454521590843797,9,6.755567729473114,38,2020,Real Madrid,2,0,22,18.711243921890855,28.303930163383484,6.194142518565059
3,FW,37,21,124,3176,21.25092190504074,8,8.153260290622711,59,2019,Real Madrid,0,0,16,17.534661665558815,31.533140420913696,10.8458740292117
4,FW,36,21,104,2972,18.669334318488836,6,6.1459240317344666,48,2018,Real Madrid,1,0,18,16.439501460641623,27.201730754226446,8.029114556498826
5,FW,32,5,63,2166,13.972143589518964,10,7.4571512043476105,44,2017,Real Madrid,0,0,3,12.485716282390058,25.422266200184822,7.880559328943491
6,Sub,29,11,69,1927,13.519236292690039,5,3.070244451984763,38,2016,Real Madrid,0,0,11,13.519236292690039,19.214677918702364,5.196352351456881
7,FW,27,24,98,2001,20.72938249260187,7,5.572381630539894,42,2015,Real Madrid,1,0,24,20.72938249260187,27.387168176472187,5.697659491561353
8,FW,29,15,69,2325,12.4124203491956,10,7.889431586489081,45,2014,Real Madrid,1,0,15,12.4124203491956,27.088969238102436,11.037378508597612

In [13]:
def radar_data(Pid: int, Role: str):
    
    url = base_url +str(Pid)
    try:
        request = requests.get(url)
    except ConnectionError as error:
        print('A connection problem', error)
        
    soup = BeautifulSoup(request.content)
    scripts  = soup.find_all('script')
    p_data = scripts[2].string
    index_start = p_data.index("('")+2
    index_end = p_data.index("')")
    json_data = p_data[index_start:index_end]
    json_data = json_data.encode('utf8').decode('unicode_escape')
    data = json.loads(json_data)
    data = pd.DataFrame.from_dict(data)
    min= ['min']
    max= ['max']
    avg= ['avg']
    
    for r in range(len(data)):
        d =json_normalize(data['{}'.format(Role)][r])
        min.append(d.iloc[0][0])
        max.append(d.iloc[0][1])
        avg.append(d.iloc[0][2])
        
    min_df=pd.DataFrame(min).T
    min_df.columns=['type','goals','xG','shots','Assists','xA','key_passes','xGChain','xGBuildup']
    max_df=pd.DataFrame(max).T
    max_df.columns=['type','goals','xG','shots','Assists','xA','key_passes','xGChain','xGBuildup']
    avg_df=pd.DataFrame(avg).T
    avg_df.columns=['type','goals','xG','shots','Assists','xA','key_passes','xGChain','xGBuildup']
    df = pd.concat([min_df,max_df,avg_df])
    df.set_index('type', inplace= True)
    return df

In [14]:
kb10_radar= radar_data(2370, 'FW')
kb10_radar

C:\Users\pc\AppData\Local\Temp\ipykernel_13708\3892848392.py:23: FutureWarning: pandas.io.json.json_normalize is deprecated, use pandas.json_normalize instead.
  d =json_normalize(data['{}'.format(Role)][r])
C:\Users\pc\AppData\Local\Temp\ipykernel_13708\3892848392.py:23: FutureWarning: pandas.io.json.json_normalize is deprecated, use pandas.json_normalize instead.
  d =json_normalize(data['{}'.format(Role)][r])
C:\Users\pc\AppData\Local\Temp\ipykernel_13708\3892848392.py:23: FutureWarning: pandas.io.json.json_normalize is deprecated, use pandas.json_normalize instead.
  d =json_normalize(data['{}'.format(Role)][r])
C:\Users\pc\AppData\Local\Temp\ipykernel_13708\3892848392.py:23: FutureWarning: pandas.io.json.json_normalize is deprecated, use pandas.json_normalize instead.
  d =json_normalize(data['{}'.format(Role)][r])
C:\Users\pc\AppData\Local\Temp\ipykernel_13708\3892848392.py:23: FutureWarning: pandas.io.json.json_normalize is deprecated, use pandas.json_normalize instead.
  d =json_normalize(data['{}'.format(Role)][r])
C:\Users\pc\AppData\Local\Temp\ipykernel_13708\3892848392.py:23: FutureWarning: pandas.io.json.json_normalize is deprecated, use pandas.json_normalize instead.
  d =json_normalize(data['{}'.format(Role)][r])
C:\Users\pc\AppData\Local\Temp\ipykernel_13708\3892848392.py:23: FutureWarning: pandas.io.json.json_normalize is deprecated, use pandas.json_normalize instead.
  d =json_normalize(data['{}'.format(Role)][r])
C:\Users\pc\AppData\Local\Temp\ipykernel_13708\3892848392.py:23: FutureWarning: pandas.io.json.json_normalize is deprecated, use pandas.json_normalize instead.
  d =json_normalize(data['{}'.format(Role)][r])

,goals,xG,shots,Assists,xA,key_passes,xGChain,xGBuildup
type,,,,,,,,
min,0.0011,0.001728,0.015,0.0,0.000264,0.0036,0.002727,0.000243
max,0.0126,0.012082,0.0737,0.0048,0.005382,0.0309,0.016914,0.006713
avg,0.0042,0.004155,0.028,0.0014,0.001316,0.012,0.005338,0.001318

In [15]:
def league_data(league: str):
    
    base_url= 'https://understat.com/league/'
    url = base_url +league
    result = requests.get(url)
    soup = BeautifulSoup(result.content)
    scripts = soup.find_all('script')
    ps_data = scripts[3].string
    index_start = ps_data.index("('")+2
    index_end = ps_data.index("')")
    json_data = ps_data[index_start:index_end]
    json_data = json_data.encode('utf8').decode('unicode_escape')
    data = json.loads(json_data)
    data = pd.DataFrame.from_dict(data)
    
    return data

In [17]:
serie_A= league_data('Serie_A')
serie_A

,id,player_name,games,time,goals,xG,assists,xA,shots,key_passes,yellow_cards,red_cards,position,team_title,npg,npxG,xGChain,xGBuildup
0,865,Marko Arnautovic,9,790,6,4.516937613487244,0,1.290935181081295,17,15,2,0,F,Bologna,4,2.994339999742806,4.8893248699605465,0.9493893515318632
1,1209,Ciro Immobile,10,814,6,6.353676936589181,3,1.0625381227582693,27,9,1,0,F,Lazio,5,4.831079243682325,7.718399939127266,2.0136421732604504
2,7084,Dusan Vlahovic,9,796,6,5.748190127313137,1,0.6827184110879898,30,11,0,0,F,Juventus,5,4.9868913516402245,4.83681857958436,1.247153103351593
3,1294,Paulo Dybala,8,599,5,4.122517980635166,2,2.9226800948381424,23,19,1,0,M,Roma,4,3.361219145357609,6.616580210626125,1.6715353764593601
4,7453,Khvicha Kvaratskhelia,10,729,5,2.9149480797350407,3,3.7128215357661247,27,20,0,0,F M S,Napoli,5,2.9149480797350407,9.379489652812481,3.512833423912525
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
469,11053,Isak Hien,8,607,0,0.04370534420013428,0,0.07128220051527023,1,2,4,0,D S,Verona,0,0.04370534420013428,0.6552195250988007,0.5839373217895627
470,11054,Juan Cabal,3,47,0,0,0,0.02738211490213871,0,1,1,0,S,Verona,0,0,0.12470605969429016,0.09732394386082888
471,11080,Valentín Carboni,1,1,0,0,0,0,0,0,0,0,S,Inter,0,0,0.04445086792111397,0.04445086792111397
472,11097,Mady Camara,4,87,0,0.06191907078027725,0,0,2,0,0,0,M S,Roma,0,0.06191907078027725,0.33034821413457394,0.30405473709106445
473,11117,Jack Hendry,1,7,0,0,0,0,0,0,0,0,S,Cremonese,0,0,0,0

In [19]:
def standings(league: str):
    
    base_url= 'https://understat.com/league/'
    url = base_url +league
    result = requests.get(url)
    soup = BeautifulSoup(result.content)
    scripts = soup.find_all('script')
    teams_data = scripts[2].string
    index_start = teams_data.index("('")+2
    index_end = teams_data.index("')")
    json_data = teams_data[index_start:index_end]
    json_data = json_data.encode('utf8').decode('unicode_escape')
    data = json.loads(json_data)
    data = pd.DataFrame.from_dict(data)
    data
    columns = ['team','M','W','D','L','G','Pts','xG','xGA','xPTS']
    team_df = pd.DataFrame()
    
    for c in range(len(data.columns)-1):
        teams_data = data.iloc[2][c]
        team = data.iloc[1][c]
        overall = json_normalize(teams_data)
        data_list = [team,len(overall),sum(overall['wins']),sum(overall['draws']),sum(overall['loses']),sum(overall['scored']),sum(overall['pts']),sum(overall['xG']),sum(overall['xGA']),sum(overall['xpts'])]
        team_df1 = pd.DataFrame(data_list).T
        team_df = pd.concat([team_df,team_df1])
        
    team_df.columns = columns
    return team_df

In [21]:
serie_A_std= standings('Serie_A')
serie_A_std

C:\Users\pc\AppData\Local\Temp\ipykernel_13708\1144415138.py:22: FutureWarning: pandas.io.json.json_normalize is deprecated, use pandas.json_normalize instead.
  overall = json_normalize(teams_data)
C:\Users\pc\AppData\Local\Temp\ipykernel_13708\1144415138.py:22: FutureWarning: pandas.io.json.json_normalize is deprecated, use pandas.json_normalize instead.
  overall = json_normalize(teams_data)
C:\Users\pc\AppData\Local\Temp\ipykernel_13708\1144415138.py:22: FutureWarning: pandas.io.json.json_normalize is deprecated, use pandas.json_normalize instead.
  overall = json_normalize(teams_data)
C:\Users\pc\AppData\Local\Temp\ipykernel_13708\1144415138.py:22: FutureWarning: pandas.io.json.json_normalize is deprecated, use pandas.json_normalize instead.
  overall = json_normalize(teams_data)
C:\Users\pc\AppData\Local\Temp\ipykernel_13708\1144415138.py:22: FutureWarning: pandas.io.json.json_normalize is deprecated, use pandas.json_normalize instead.
  overall = json_normalize(teams_data)
C:\Users\pc\AppData\Local\Temp\ipykernel_13708\1144415138.py:22: FutureWarning: pandas.io.json.json_normalize is deprecated, use pandas.json_normalize instead.
  overall = json_normalize(teams_data)
C:\Users\pc\AppData\Local\Temp\ipykernel_13708\1144415138.py:22: FutureWarning: pandas.io.json.json_normalize is deprecated, use pandas.json_normalize instead.
  overall = json_normalize(teams_data)
C:\Users\pc\AppData\Local\Temp\ipykernel_13708\1144415138.py:22: FutureWarning: pandas.io.json.json_normalize is deprecated, use pandas.json_normalize instead.
  overall = json_normalize(teams_data)
C:\Users\pc\AppData\Local\Temp\ipykernel_13708\1144415138.py:22: FutureWarning: pandas.io.json.json_normalize is deprecated, use pandas.json_normalize instead.
  overall = json_normalize(teams_data)
C:\Users\pc\AppData\Local\Temp\ipykernel_13708\1144415138.py:22: FutureWarning: pandas.io.json.json_normalize is deprecated, use pandas.json_normalize instead.
  overall = json_normalize(teams_data)
C:\Users\pc\AppData\Local\Temp\ipykernel_13708\1144415138.py:22: FutureWarning: pandas.io.json.json_normalize is deprecated, use pandas.json_normalize instead.
  overall = json_normalize(teams_data)
C:\Users\pc\AppData\Local\Temp\ipykernel_13708\1144415138.py:22: FutureWarning: pandas.io.json.json_normalize is deprecated, use pandas.json_normalize instead.
  overall = json_normalize(teams_data)
C:\Users\pc\AppData\Local\Temp\ipykernel_13708\1144415138.py:22: FutureWarning: pandas.io.json.json_normalize is deprecated, use pandas.json_normalize instead.
  overall = json_normalize(teams_data)
C:\Users\pc\AppData\Local\Temp\ipykernel_13708\1144415138.py:22: FutureWarning: pandas.io.json.json_normalize is deprecated, use pandas.json_normalize instead.
  overall = json_normalize(teams_data)
C:\Users\pc\AppData\Local\Temp\ipykernel_13708\1144415138.py:22: FutureWarning: pandas.io.json.json_normalize is deprecated, use pandas.json_normalize instead.
  overall = json_normalize(teams_data)
C:\Users\pc\AppData\Local\Temp\ipykernel_13708\1144415138.py:22: FutureWarning: pandas.io.json.json_normalize is deprecated, use pandas.json_normalize instead.
  overall = json_normalize(teams_data)
C:\Users\pc\AppData\Local\Temp\ipykernel_13708\1144415138.py:22: FutureWarning: pandas.io.json.json_normalize is deprecated, use pandas.json_normalize instead.
  overall = json_normalize(teams_data)
C:\Users\pc\AppData\Local\Temp\ipykernel_13708\1144415138.py:22: FutureWarning: pandas.io.json.json_normalize is deprecated, use pandas.json_normalize instead.
  overall = json_normalize(teams_data)
C:\Users\pc\AppData\Local\Temp\ipykernel_13708\1144415138.py:22: FutureWarning: pandas.io.json.json_normalize is deprecated, use pandas.json_normalize instead.
  overall = json_normalize(teams_data)

          team   M  W  D  L   G Pts         xG        xGA     xPTS
0       Verona  10  1  2  7   9   5  11.082227  15.919603  10.6354
0         Roma  10  7  1  2  13  22  24.770726   6.138323  24.0878
0        Lazio  10  6  3  1  21  21  15.711439   12.52598  15.2702
0      Bologna  10  1  4  5  10   7  11.307859  18.930735  10.3635
0     Juventus  10  4  4  2  13  16  15.096102  12.552597  15.1231
0      Udinese  10  6  3  1  19  21  13.781255   10.76552  16.1778
0    Sampdoria  10  0  3  7   5   3    7.87838  16.005021   7.8802
0     Sassuolo  10  3  3  4  12  12  12.982436  14.314454  12.9785
0       Napoli  10  8  2  0  25  26   25.02996   8.432055  22.9982
0        Inter  10  6  0  4  18  18  19.581406   9.218295  20.9199
0     Atalanta  10  7  3  0  16  24  15.479874  10.056766  18.3635
0       Empoli  10  2  5  3   9  11  10.027292  16.666904  10.1259
0   Fiorentina  10  2  4  4   8  10  13.076352  13.480779  12.7228
0     AC Milan  10  7  2  1  20  23  20.173576  10.347249  20.2894
0       Torino  10  3  2  5   8  11  13.534852  11.572198  15.0607
0        Lecce  10  1  5  4   9   8   9.408383  13.436267  12.0357
0       Spezia  10  2  3  5   9   9   7.931374  18.463017   6.8693
0  Salernitana  10  2  4  4  12  10  11.726545  18.156244  10.2845
0        Monza  10  3  1  6   9  10   9.078863   18.73878   8.5883